"""initial schema

Revision ID: a9ef2b2e61c9
Revises: 
Create Date: 2026-03-24 23:07:20.649887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9ef2b2e61c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('salary_range', sa.String(length=200), nullable=True),
    sa.Column('job_type', sa.String(length=100), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    op.create_index('idx_jobs_scraped_at', 'jobs', ['scraped_at'], unique=False)
    op.create_index('idx_jobs_source', 'jobs', ['source'], unique=False)
    op.create_index('idx_jobs_source_url', 'jobs', ['source_url'], unique=True)
    op.create_table('resumes',
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('parsed_text', sa.Text(), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_index('idx_resumes_content_hash', 'resumes', ['content_hash'], unique=True)
    op.create_table('tailored_resumes',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('prompt_used', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('output_path', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tr_job_id', 'tailored_resumes', ['job_id'], unique=False)
    op.create_index('idx_tr_resume_id', 'tailored_resumes', ['resume_id'], unique=False)
    op.create_index('idx_tr_status', 'tailored_resumes', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tr_status', table_name='tailored_resumes')
    op.drop_index('idx_tr_resume_id', table_name='tailored_resumes')
    op.drop_index('idx_tr_job_id', table_name='tailored_resumes')
    op.drop_table('tailored_resumes')
    op.drop_index('idx_resumes_content_hash', table_name='resumes')
    op.drop_table('resumes')
    op.drop_index('idx_jobs_source_url', table_name='jobs')
    op.drop_index('idx_jobs_source', table_name='jobs')
    op.drop_index('idx_jobs_scraped_at', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
